#!/usr/bin/env python3
from pathlib import Path
import argparse
import json
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parent


def run_script(name: str, args: list[str]) -> int:
    command = [sys.executable, str(ROOT / "scripts" / name), *args]
    return subprocess.run(command, cwd=ROOT).returncode


def load_state(project: Path) -> dict:
    state_path = project / ".codex-memory" / "STATE.json"
    if not state_path.is_file():
        raise SystemExit(f"ERROR: missing state file: {state_path}")
    return json.loads(state_path.read_text(encoding="utf-8"))


def save_state(project: Path, state: dict) -> None:
    state_path = project / ".codex-memory" / "STATE.json"
    state_path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_starter(project: Path, state: dict) -> dict:
    starter_path = project / ".pfo-starter.json"
    if starter_path.is_file():
        return json.loads(starter_path.read_text(encoding="utf-8"))
    starter_id = state.get("starter") or "saas-fastapi-vue"
    starter_file = ROOT / "starters" / starter_id / "STARTER.json"
    if starter_file.is_file():
        return json.loads(starter_file.read_text(encoding="utf-8"))
    return {
        "id": "custom",
        "productType": state.get("productTypeHint", "web_app"),
        "stack": [],
        "folders": [],
        "commands": {},
        "requiredArtifacts": [],
    }


def write_if_missing(path: Path, text: str) -> bool:
    if path.exists():
        return False
    path.write_text(text, encoding="utf-8")
    return True


def generated_blueprint(project: Path, state: dict, starter: dict) -> str:
    idea = state.get("intent") or "Product idea not captured yet."
    product_type = starter.get("productType") or state.get("productTypeHint") or ""
    stack = ", ".join(starter.get("stack", [])) or "project-specific stack"
    modules = starter.get("folders", [])
    module_rows = "\n".join(
        f"| {folder} | Runtime area generated by starter `{starter.get('id', 'custom')}` | TBD | starter contract |"
        for folder in modules[:8]
    ) or "| core | Product runtime core | TBD | custom contract |"
    return f"""# Product Blueprint

## Product Classification

```text
PRODUCT_TYPE: {product_type}
DOMAIN: TBD from discovery
COMPLEXITY: TBD
REQUIRED_MODULES: {', '.join(modules) if modules else 'TBD'}
INFRASTRUCTURE: {stack}
```

## Initial Intent

{idea}

## Business Logic

Describe the smallest useful value loop before implementation.

## Users And Roles

- Primary user: TBD
- Operator/admin: TBD

## Core Entities

| Entity | Purpose | Fields | Relationships |
|---|---|---|---|
| User | Person or account using the product | id, contact, status | owns product actions |
| Work Item | Main product object | id, state, timestamps | belongs to user |

## Modules

| Module | Responsibility | Depends On | Template Contract |
|---|---|---|---|
{module_rows}

## Interfaces

- Pages: TBD
- API: TBD
- Commands: TBD
- Bot handlers: TBD
- CLI commands: TBD

## Infrastructure

- Runtime: {stack}
- Database: TBD
- Queue: TBD
- Storage: TBD
- Deployment target: TBD

## Risks And Assumptions

- Validate unclear requirements before writing production behavior.
- Keep `.pfo/` contracts authoritative for scope, data, fallback, and golden-flow rules.
"""


def generated_architecture(starter: dict) -> str:
    stack = ", ".join(starter.get("stack", [])) or "TBD"
    commands = starter.get("commands", {})
    command_rows = "\n".join(f"- `{name}`: `{command}`" for name, command in commands.items()) or "- TBD"
    return f"""# PROJECT_ARCHITECTURE

## Stack

{stack}

## Rationale

Use the selected starter `{starter.get('id', 'custom')}` as the initial architecture baseline. Replace defaults only when product requirements require it.

## Data Model

Define entities in `PRODUCT_BLUEPRINT.md`, then turn them into migrations or schema files during the relevant execution graph node.

## API, Pages, Commands, Or Handlers

TBD by product interface.

## Auth And Permissions

Start with least privilege. Add auth only when the product flow requires persistent users, private data, payments, admin operations, or integrations.

## Integrations

TBD.

## Deployment Topology

Use generated CI and starter commands first:

{command_rows}

## Observability

Add health checks, structured logs, and error reporting before `READY_FOR_DEPLOY`.

## Risks And Tradeoffs

- Starter defaults are scaffolding, not final product truth.
- Deployment is blocked until tests, review, security, dependency, hardening, and `.pfo/` contract gates are explicit.
"""


def generated_build_plan(starter: dict) -> str:
    commands = starter.get("commands", {})
    test_command = commands.get("backendTest") or commands.get("frontendTest") or "project test command"
    build_command = commands.get("build") or "project build command"
    return f"""# Build Plan

## Module Order

| Step | Module | Dependencies | Files Likely Touched | Verification | Exit Criteria |
|---:|---|---|---|---|---|
| 1 | Starter baseline and contracts | CODEX.md, `.pfo/` | starter files, `.env.example`, CI | `python3 scripts/pfo.py validate <project>` | project validates under PFO |
| 2 | Product domain model | PRODUCT_BLUEPRINT.md | backend, database, shared types | `{test_command}` | core entities covered by tests |
| 3 | Primary user flow | domain model | frontend, API, bot, or CLI handlers | smoke path from TEST_PLAN.md | golden flow documented and verified |
| 4 | Quality gates | implemented flow | TEST_PLAN.md, QUALITY_GATES.md | review/security/deps/harden gates | no critical blocker remains |
| 5 | Deploy readiness | quality gates | Docker, CI, docs, rollback notes | `{build_command}` | READY_FOR_DEPLOY can be reached |

## Cross-Module Dependencies

- Implementation order follows `EXECUTION_GRAPH.md`.
- Any change touching a golden flow must update `.pfo/GOLDEN_FLOWS.md` evidence.

## Test Strategy

- Use starter commands where available.
- Add focused regression tests for changed behavior.
- Browser-facing products require `/browser-check` before deploy readiness.

## Gate Strategy

- Run `.pfo/` contract gate on every meaningful diff.
- Deployment requires explicit user confirmation and non-blocked gates.

## Deferred Work

- Non-MVP modules stay out of scope until `SCOPE_LOCK.md` is updated.
"""


def generated_test_plan(starter: dict) -> str:
    commands = starter.get("commands", {})
    backend = commands.get("backendTest", "TBD")
    frontend = commands.get("frontendTest", "TBD")
    build = commands.get("build", "TBD")
    return f"""# Test Plan

## Product Type

{starter.get('productType', 'TBD')}

## Test Matrix

| Layer | Scope | Command | Required For |
|---|---|---|---|
| Backend | domain logic, API, integrations | `{backend}` | behavior changes |
| Frontend/UI | critical user flows | `{frontend}` | browser-facing changes |
| Build | deployable artifact | `{build}` | deploy readiness |
| PFO contracts | scope/data/fallback/golden flows | `python3 scripts/pfo_contract_gate.py <project>` | every meaningful diff |

## Critical Flows

- Define one primary golden flow before implementation.
- Add at least one smoke path that can be verified locally.

## Negative And Edge Cases

- Invalid input.
- Missing external provider.
- Permission boundary.
- Empty or unavailable data source.

## Smoke Path

TBD by product type.

## CI Requirements

- Generated CI must run tests, contract gate, and build checks that are available for the starter.
"""


def generated_quality_gates() -> str:
    return """# Quality Gates

## Gate Results

| Gate | Status | Evidence | Blockers |
|---|---|---|---|
| Strategy | PENDING | DISCOVERY.md / MARKET_BRIEF.md when applicable |  |
| Architecture | PENDING | PRODUCT_BLUEPRINT.md, PROJECT_ARCHITECTURE.md, BUILD_PLAN.md |  |
| Tests | PENDING | TEST_PLAN.md and test command output |  |
| Review | PENDING | `/review` result |  |
| Security | PENDING | `/security-audit` or accepted not-applicable note |  |
| Dependencies | PENDING | `/deps-audit` or accepted not-applicable note |  |
| Hardening | PENDING | `/harden` or accepted non-production note |  |
| Scope Lock | PENDING | `.pfo/SCOPE_LOCK.md`, diff review |  |
| Data Authenticity | PENDING | `.pfo/DATA_POLICY.md`, data-source evidence |  |
| Golden Flows | PENDING | `.pfo/GOLDEN_FLOWS.md`, tests/manual verification |  |
| Regression Contract | PENDING | `.pfo/PROJECT_CONTRACT.md`, behavior checks |  |
| Fallback Policy | PENDING | `.pfo/FALLBACK_POLICY.md`, degraded-mode checks |  |
| Diff Risk | PENDING | `PFO_CONTRACT_GATE.json` when generated |  |
| No Silent Substitution | PENDING | diff scan, project contracts |  |
| Deployment Readiness | PENDING | env vars, build, health check, rollback notes |  |

## Accepted Risks

None yet.

## Next Gate

Run `/review`, `/test`, `/security-audit`, `/deps-audit`, and `/harden` as applicable before deploy readiness.
"""


def cmd_new(args: argparse.Namespace) -> int:
    return run_script("pfo_new_project.py", [args.name, "--idea", args.idea, "--workspace", str(args.workspace)])


def cmd_adopt(args: argparse.Namespace) -> int:
    argv = ["--write"]
    if args.project:
        argv.extend(["--project", str(args.project)])
    else:
        argv.extend(["--workspace", str(args.workspace)])
    if args.json:
        argv.append("--json")
    code = run_script("adoption_check.py", argv)
    if code == 0 and args.analyze and args.project:
        analyze_args = [str(args.project)]
        if args.run_gates:
            analyze_args.append("--run-gates")
        return run_script("existing_project_analyzer.py", analyze_args)
    return code


def cmd_analyze(args: argparse.Namespace) -> int:
    argv = [str(args.project)]
    if args.run_gates:
        argv.append("--run-gates")
    if args.json:
        argv.append("--json")
    argv.extend(["--timeout", str(args.timeout)])
    code = run_script("existing_project_analyzer.py", argv)
    if code == 0 and args.report:
        return run_script("pfo_report.py", [str(args.project)])
    return code


def cmd_status(args: argparse.Namespace) -> int:
    project = args.project.resolve()
    state = load_state(project)
    print(json.dumps({
        "project": str(project),
        "currentStage": state.get("currentStage"),
        "currentNode": state.get("currentNode"),
        "nextAction": state.get("nextAction"),
        "blockers": state.get("blockers", []),
        "gateResults": state.get("gateResults", {}),
    }, indent=2, ensure_ascii=False))
    return 0


def cmd_plan(args: argparse.Namespace) -> int:
    project = args.project.resolve()
    state = load_state(project)
    starter = load_starter(project, state)
    written = []
    for path, text in [
        (project / "PRODUCT_BLUEPRINT.md", generated_blueprint(project, state, starter)),
        (project / "PROJECT_ARCHITECTURE.md", generated_architecture(starter)),
        (project / "BUILD_PLAN.md", generated_build_plan(starter)),
        (project / "TEST_PLAN.md", generated_test_plan(starter)),
        (project / "QUALITY_GATES.md", generated_quality_gates()),
    ]:
        if write_if_missing(path, text):
            written.append(path.name)
    graph = project / "EXECUTION_GRAPH.md"
    if not graph.exists():
        code = run_script("generate_execution_graph.py", [str(project)])
        if code != 0:
            return code
        written.append("EXECUTION_GRAPH.md")
    state["currentStage"] = "PLAN_READY"
    state["classification"]["productType"] = state["classification"].get("productType") or starter.get("productType", "")
    state["architecture"]["backend"] = state["architecture"].get("backend") or ", ".join(starter.get("stack", []))
    artifacts = set(state.get("artifacts", []))
    artifacts.update([
        "PRODUCT_BLUEPRINT.md",
        "PROJECT_ARCHITECTURE.md",
        "BUILD_PLAN.md",
        "EXECUTION_GRAPH.md",
        "TEST_PLAN.md",
        "QUALITY_GATES.md",
    ])
    state["artifacts"] = sorted(artifacts)
    state["nextAction"] = "Review generated planning artifacts, resolve TBD fields, then run /review before build."
    state.setdefault("decisionLog", []).append({"event": "pfo plan requested", "note": args.note})
    save_state(project, state)
    print("OK: plan stage recorded")
    if written:
        print("Generated: " + ", ".join(written))
    else:
        print("Generated: none; existing artifacts preserved")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    return run_script("pfo_runner.py", [str(args.project), "--mode", "build"])


def cmd_test(args: argparse.Namespace) -> int:
    return run_script("pfo_runner.py", [str(args.project), "--mode", "test"])


def cmd_review(args: argparse.Namespace) -> int:
    return run_script("pfo_runner.py", [str(args.project), "--mode", "review"])


def cmd_validate(args: argparse.Namespace) -> int:
    return run_script("validate_project.py", [str(args.project)])


def cmd_contracts(args: argparse.Namespace) -> int:
    argv = [str(args.project)]
    if args.json:
        argv.append("--json")
    if args.write:
        argv.append("--write")
    if args.strict:
        argv.append("--strict")
    return run_script("pfo_contract_gate.py", argv)


def cmd_resume(args: argparse.Namespace) -> int:
    project = args.project.resolve()
    state = load_state(project)
    print("CURRENT STATE:", state.get("currentStage", ""))
    print("CURRENT NODE:", state.get("currentNode", ""))
    print("NEXT ACTION:", state.get("nextAction", ""))
    return 0


def cmd_voice(args: argparse.Namespace) -> int:
    return run_script("voice_intent.py", [args.text, "--workspace", str(args.workspace)])


def cmd_metrics(args: argparse.Namespace) -> int:
    return run_script("pfo_metrics.py", [str(args.workspace)])


def cmd_report(args: argparse.Namespace) -> int:
    return run_script("pfo_report.py", [str(args.project)])


def cmd_export(args: argparse.Namespace) -> int:
    return run_script("export_integrations.py", [str(args.project), "--target", args.target])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="pfo", description="Product Factory OS runtime CLI.")
    sub = parser.add_subparsers(dest="command", required=True)

    new = sub.add_parser("new", help="Bootstrap a new PFO project.")
    new.add_argument("name")
    new.add_argument("--idea", default="")
    new.add_argument("--workspace", type=Path, default=WORKSPACE)
    new.set_defaults(func=cmd_new)

    adopt = sub.add_parser("adopt", help="Adopt existing workspace projects into PFO.")
    adopt.add_argument("project", type=Path, nargs="?")
    adopt.add_argument("--workspace", type=Path, default=WORKSPACE)
    adopt.add_argument("--json", action="store_true")
    adopt.add_argument("--analyze", action="store_true", help="Run existing-project analyzer after adopting a single project.")
    adopt.add_argument("--run-gates", action="store_true", help="Run detected gates during analysis.")
    adopt.set_defaults(func=cmd_adopt)

    analyze = sub.add_parser("analyze", help="Analyze an existing project, detect stack/commands, run gates, and update PFO state.")
    analyze.add_argument("project", type=Path)
    analyze.add_argument("--run-gates", action="store_true")
    analyze.add_argument("--timeout", type=int, default=90)
    analyze.add_argument("--json", action="store_true")
    analyze.add_argument("--report", action="store_true", help="Regenerate PFO_REPORT.md after analysis.")
    analyze.set_defaults(func=cmd_analyze)

    for name, func in [
        ("status", cmd_status),
        ("plan", cmd_plan),
        ("build", cmd_build),
        ("test", cmd_test),
        ("review", cmd_review),
        ("validate", cmd_validate),
        ("contracts", cmd_contracts),
        ("resume", cmd_resume),
        ("report", cmd_report),
    ]:
        item = sub.add_parser(name)
        item.add_argument("project", type=Path)
        if name == "plan":
            item.add_argument("--note", default="")
        if name == "contracts":
            item.add_argument("--json", action="store_true")
            item.add_argument("--write", action="store_true")
            item.add_argument("--strict", action="store_true")
        item.set_defaults(func=func)

    voice = sub.add_parser("voice", help="Normalize a voice command into PFO intent.")
    voice.add_argument("text")
    voice.add_argument("--workspace", type=Path, default=WORKSPACE)
    voice.set_defaults(func=cmd_voice)

    metrics = sub.add_parser("metrics", help="Collect workspace PFO metrics.")
    metrics.add_argument("--workspace", type=Path, default=WORKSPACE)
    metrics.set_defaults(func=cmd_metrics)

    export = sub.add_parser("export", help="Export project state for external tools.")
    export.add_argument("project", type=Path)
    export.add_argument("--target", choices=["github", "linear", "notion", "google-drive"], required=True)
    export.set_defaults(func=cmd_export)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    raise SystemExit(args.func(args))


if __name__ == "__main__":
    main()
